mode: ContinuousDeployment
branches:
  main:
    regex: ^main$
    increment: Major
    tag: ''
    prevent-increment-of-merged-branch-version: false

  feat:
    regex: ^(feat|feature)[/-]
    increment: Minor
    tag: 'useBranchName'
    prevent-increment-of-merged-branch-version: true

  dev:
    regex: ^dev[/-]
    increment: Patch
    tag: 'useBranchName'
    prevent-increment-of-merged-branch-version: true

  other:
    regex: .*
    increment: Patch
    tag: 'useBranchName'
    prevent-increment-of-merged-branch-version: true