version: "3.9"

services:
  traefik:
    deploy:
      replicas: 0

  obs:
    build:
      context: ./pi-obs-container
      dockerfile: Dockerfile.arm64
    networks:
      - rtmp_network
    ports:
      - "5800:5800"
      - "5900:5900"
      - "4455:4455"
      - "6080:6080"
    labels: []

  rtmp-server:
    build:
      context: ./rtmp-server
    networks:
      - rtmp_network
    ports:
      - "1935:1935"
      - "18080:8080"
    labels: []

  metadata-service:
    build:
      context: ./metadata-service
    networks:
      - rtmp_network
    ports:
      - "5000:5000"
    labels: []

  rabbitmq:
    networks:
      - rtmp_network
    ports:
      - "5672:5672"
      - "15672:15672"
    labels: []

networks:
  tailscale:
    external: false
    name: disable_tailscale  # prevents compose errors