version: "3.9"

services:
  traefik:
    deploy:
      replicas: 0

  obs:
    ports:
      - "5800:5800"  # noVNC
      - "5900:5900"  # native VNC
      - "4455:4455"  # OBS WebSocket
      - "6080:6080"
    labels: []
    networks:
      - rtmp_network
    command: >
      bash -c "
        echo '[INIT] Ensuring v4l2loopback is loaded...' &&
        modprobe v4l2loopback devices=1 video_nr=10 card_label='obs_gui_stream' exclusive_caps=1 2>/dev/null || echo '[WARN] Failed to modprobe v4l2loopback' &&
        /entrypoint.sh
      "

  rtmp-server:
    ports:
      - "1935:1935"  # RTMP
      - "18080:8080"  # HTTP
    labels: []
    networks:
      - rtmp_network

  metadata-service:
    labels: []
    networks:
      - rtmp_network

networks:
  rtmp_network:
    external: true
    name: rtmp_network