services:
  ndi-sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    image: cdaprod/open-ndi-sender:latest
    networks:
      - ndi-net
    ports:
      - "9000:9000"       # control TCP
      - "5000:5000/udp"   # media UDP

  ndi-receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    image: cdaprod/open-ndi-receiver:latest
    networks:
      - ndi-net
    environment:
      - DISPLAY=:0
    devices:
      - /dev/video0  # Only needed if decoding from camera
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["/usr/local/bin/open-ndi-receiver", "--preview"]

  open-ndi-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: cdaprod/open-ndi-cli:latest
    entrypoint: ["/usr/local/bin/open-ndi-cli"]
    
networks:
  ndi-net:
    driver: bridge