services:
  ndi-sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    image: cdaprod/open-ndi-sender:latest
    networks:
      - ndi-net
    ports:
      - "9000:9000"       # control TCP
      - "5000:5000/udp"   # media UDP

  ndi-receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    image: cdaprod/open-ndi-receiver:latest
    networks:
      - ndi-net

networks:
  ndi-net:
    driver: bridge