version: "3.9"

services:
  obs-pi:
    build: ./pi-obs-container
    container_name: obs_pi
    privileged: true
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:/config
      - ./background.mp4:/root/background.mp4
      - ./frame_overlay.png:/root/frame_overlay.png
    network_mode: host