services:
  obs-pi:
    build: ./pi-obs-container
    container_name: obs_pi
    privileged: true
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:/config
      # Map all background and overlay assets
      - ../assets/backgrounds/BG_AURORA_PORTRAIT.gif:/root/assets/backgrounds/BG_AURORA_PORTRAIT.gif
      - ../assets/backgrounds/BG_VORTEX_PORTRAIT.gif:/root/assets/backgrounds/BG_VORTEX_PORTRAIT.gif
      - ../assets/backgrounds/BG_VORTEX_LANDSCAPE.gif:/root/assets/backgrounds/BG_VORTEX_LANDSCAPE.gif
      - ../assets/backgrounds/BG_AURORA_LANDSCAPE.gif:/root/assets/backgrounds/BG_AURORA_LANDSCAPE.gif
      - ../assets/overlays/iphone_frame_overlay.png:/root/assets/overlays/iphone_frame_overlay.png
    ports:
      - "6080:6080" # noVNC port
      - "5900:5900" # VNC port
      - "4455:4455" # OBS WebSockets
    labels:
      com.cdaprod.project: "Pi OBS Container"
      com.cdaprod.version: "1.1.0"
      com.cdaprod.description: "Enhanced OBS server with portable multi-source streaming"
      com.cdaprod.maintainer: "Cdaprod <Cdaprod@Cdaprod.dev>"
    networks:
      - rtmp_network

networks:
  rtmp_network:
    driver: bridge