version: "3.9"

services:
  obs-pi:
    build: ./pi-obs-container
    container_name: obs_pi
    privileged: true
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:/config
      - ./background.mp4:/root/background.mp4
      - ./frame_overlay.png:/root/frame_overlay.png
    ports:
      - "6080:6080" # noVNC port
      - "5900:5900" # VNC port
      - "4455:4455" # OBS WebSockets
    network_mode: host