version: "3.9"

services:
  obs:
    build:
      context: ./pi-obs-container
      dockerfile: Dockerfile.arm64
    container_name: obs-pi
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - "5800:5800"  # noVNC
      - "5900:5900"  # native VNC
      - "4455:4455"  # OBS WebSocket
    devices:
      - /dev/video0
    volumes:
      - ./config:/root/.config/obs-studio
      - ./../assets:/root/assets
      #- ./recordings:/recordings
      - ./scripts:/root/scripts
    networks:
      - rtmp_network