# services/sanity-studio/docker-compose.yaml
services:
  sanity-studio:
    build:
      context: ./services/sanity-studio
    image: cdaprod/sanity-studio:latest
    container_name: sanity-studio
    env_file:
      - services/sanity-studio/.env
    volumes:
      - ./services/sanity-studio:/app
    ports:
      - "3333:3333"
    depends_on:
      - minio
      - metadata-service
    networks:
      - storage_network
      - event_network