from datetime import datetime
from typing import Dict, Any
import os

def default_metadata(video_path: str, thumb_path: str) -> Dict[str, Any]:
    """Default CDA Metadata."""
    base = os.path.basename(video_path)
    return {
        "video_filename": base,
        "thumbnail_filename": os.path.basename(thumb_path),
        "sha256_hash": calculate_sha256(video_path),
        "generated_by": "CDA Metadata Finalizer",
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "title": f"CDA Artifact: {os.path.splitext(base)[0]}",
        "description": "Automatically generated by CDA pipeline",
        "tags": ["CDAProd", "AI", "Metadata", "Automated"]
    }

def blackbox_stock_metadata(video_path: str, thumb_path: str) -> Dict[str, Any]:
    """BlackBox Global Stock Video Metadata Profile."""
    base = os.path.basename(video_path)
    file_name, _ = os.path.splitext(base)
    return {
        "title": f"{file_name} 01",  # First increment
        "description": f"A beautifully captured scene featuring {file_name}.",  # Example only
        "keywords": ["nature", "landscape", "sunset", "travel", "exploration", "USA"],
        "batch_name": "Batch_2025_01",  # Dynamic or predefined
        "category": "Nature/Landscape",
        "editorial": "No",
        "shooting_country": "USA",
        "shooting_date": datetime.utcnow().strftime("%Y-%m-%d")
    }

# Master registry
METADATA_PROFILES = {
    "default": default_metadata,
    "blackbox_stock": blackbox_stock_metadata
}