services:
  blender:
    build: ./blender-docker
    networks:
      - app_network
    ports:
      - "25800:5800"
      - "25900:5900"
      - "25000:5000"
    volumes:
      - ./blendfiles:/workspace
      - /mnt/b:/mnt/b
    environment:
      - DISPLAY=:0

networks:
  app_network:
    external: true