version: '3.9'
networks:
  core_net:
    name: core_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

  rtmp_net:
    name: rtmp_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

  media_net:
    name: media_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24

  webrtc_net:
    name: webrtc_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24

  traefik_net:
    name: traefik_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.4.0/24

  tailscale:
    external: true