name: CI-Build

on:
  push:
    branches:
      - '**'  # Matches all branches
    tags:
      - '**'  # Matches all tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # Specify the desired version

      # Step 3: Build and run services with graceful error handling
      - name: Build and run services
        run: |
          set -e
          docker-compose up -d || echo "Docker Compose failed to start all services, but we're continuing gracefully."
          
      # Step 4: Cleanup services (always runs to ensure cleanup happens)
      - name: Cleanup Docker Compose
        if: always()  # Ensures this step runs even if previous steps fail
        run: |
          echo "Cleaning up Docker Compose services..."
          docker-compose down || echo "Failed to bring down Docker Compose services, continuing..."