name: Publish OBS Runtime Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # OPTIONAL: uncomment for GitHub Container Registry
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push obs-runtime-builder
        uses: docker/build-push-action@v5
        with:
          context: ./src/dockerfiles/obs-runtime-builder
          file: ./src/dockerfiles/obs-runtime-builder/Dockerfile
          push: true
          tags: |
            cdaprod/obs-runtime-builder:latest
            cdaprod/obs-runtime-builder:${{ github.ref_name }}